server:
  port: 8081
  servlet:
    context-path: /backup

spring:
  application:
    name: backup

# backup datasource
backup:
  datasource:
    host: localhost
    userName: root
    password: 123456
    database: kitty